import Vue from 'vue'
import { Button, Form, FormItem, Input, Tabs, TabPane, Container, Header, Row, Col, Main, ButtonGroup, Message, Aside, Menu, Submenu, MenuItem, Breadcrumb, BreadcrumbItem, Card, Table, TableColumn, Switch, Tooltip, Pagination, Dialog, MessageBox, Tag, Select, Option, Tree, Cascader, Alert, Step, Steps, Footer, Carousel, CarouselItem, Backtop, Divider, Link, Avatar, Checkbox, Progress, Dropdown, DropdownItem, DropdownMenu, Upload, DatePicker } from 'element-ui'
Vue.use(Button)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Form)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Container)
Vue.use(Header)
Vue.use(Row)
Vue.use(Col)
Vue.use(Main)
Vue.use(ButtonGroup)
Vue.use(Aside)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(TableColumn)
Vue.use(Table)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tree)
Vue.use(Cascader)
Vue.use(Alert)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Footer)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Backtop)
Vue.use(Divider)
Vue.use(Link)
Vue.use(Avatar)
Vue.use(Checkbox)
Vue.use(Progress)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Dropdown)
Vue.use(Upload)
Vue.use(DatePicker)
// 将弹框组件挂载到Vue的原型对象上，这样每个组件可以通过this来访问到$message
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
